# setting number of test case for unseen eval
test_case_num: 100
train_way: 12
test_way: 1



# data parameters
dataset_path: ../amc_dataset/RML2018
save_path: checkpoint/paper/unseen/vit
epoch: 50

# supervised learning parameters
model_name: resnet
batch_size: 128

# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
lr: 0.01
lr_gamma: 0.8
print_iter: 400

# test parameters
test_dataset_path: ../amc_dataset/RML2018
load_test_path: checkpoint/paper/unseen/vit
show_conf_matrix: False

# AMC dataset configuration
# easy: [0, 1, 3, 4, 5, 12, 18, 20, 21, 22, 23]
# difficult: [2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19]
# all: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
total_class: ['OOK', '4ASK', '8ASK', 'BPSK', 'QPSK', '8PSK', '16PSK', '32PSK', '16APSK', '32APSK', '64APSK', '128APSK', '16QAM', '32QAM', '64QAM', '128QAM', '256QAM', 'AM-SSB-WC', 'AM-SSB-SC', 'AM-DSB-WC', 'AM-DSB-SC', 'FM', 'GMSK', 'OQPSK']
class_indice: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

testA: [2, 3, 7, 8, 10, 11, 15, 17, 18, 20, 22, 23]
testB: [1, 3, 5, 7, 9, 10, 11, 14, 17, 19, 21, 22]
testC: [2, 3, 4, 6, 7, 9, 13, 15, 17, 19, 21, 22]
testB_1shot: [1, 3, 5, 7, 9, 10, 11, 14, 17, 19, 21, 22]
testB_10shot: [1, 3, 5, 7, 9, 10, 11, 14, 17, 19, 21, 22]
testB_15shot: [1, 3, 5, 7, 9, 10, 11, 14, 17, 19, 21, 22]
select_test: testB

# few-shot learning parameters
fs_model: vit # robustcnn, rewis, vit
num_support: 15
num_query: 10

##### unseen test parameters
### train
snr_range: [-10, 20]
train_sample_size: 1024
test_sample_size: [1024]
train_proportion: 0.8
data_divide: True  # divide train, test dataset

### test
test_snr_range: [-20,20]
load_model_name: 49.tar

# transformer parameters
trans_lr: 0.001

in_channels: 1
patch_size: [2, 16] #12
embed_dim: 36
num_layers: 8
num_heads: 9
mlp_dim: 32
in_size: [2,1024]
num_classes: 24
