# data parameters
dataset_path: /home/inclab2/Gitrepo/WiReal/amc_dataset/RML2018
save_path: checkpoint/paper/size/resnet
epoch: 50

# supervised learning parameters
model_name: resnet
batch_size: 128

# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
lr: 0.01
lr_gamma: 0.8
print_iter: 400

# test parameters
test_dataset_path: /home/inclab2/Gitrepo/WiReal/amc_dataset/RML2018
load_test_path: checkpoint/paper/size/resnet
show_conf_matrix: True

# AMC dataset configuration
total_class: ['OOK', '4ASK', '8ASK', 'BPSK', 'QPSK', '8PSK', '16PSK', '32PSK', '16APSK', '32APSK', '64APSK', '128APSK', '16QAM', '32QAM', '64QAM', '128QAM', '256QAM', 'AM-SSB-WC', 'AM-SSB-SC', 'AM-DSB-WC', 'AM-DSB-SC', 'FM', 'GMSK', 'OQPSK']
easy_class_indice: [0, 1, 3, 4, 5, 12, 18, 20, 21, 22, 23, 2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19] # [2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19]
difficult_class_indice: [0, 1, 3, 4, 5, 12, 18, 20, 21, 22, 23, 2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19]

# few-shot learning parameters
fs_model: rewis # robustcnn, rewis, vit
num_support: 5
num_query: 10

##### Size test parameters
### train
snr_range: [-10, 20]
train_sample_size: 1024
test_sample_size: [16, 32, 64, 128, 256, 512, 1024]
save_folder_name: -10to20_1024_all
train_proportion: 0.8
data_divide: True  # divide train, test dataset

### test
test_snr_range: [-20,20]
load_model_name: 49.tar

# transformer parameters
trans_lr: 0.001

in_channels: 1
patch_size: [2, 16] #12
embed_dim: 36
num_layers: 8
num_heads: 9
mlp_dim: 32
in_size: [2,1024]
num_classes: 24
