# data parameters
dataset_path: C:\Users\user\Documents\GitHub\WiReal\amc_dataset\RML2018
snr_range: [20, 20]
save_path: checkpoint/few_shot
epoch: 30

# supervised learning parameters
model_name: robustcnn
batch_size: 128

# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
train_proportion: 0.8
lr: 0.001
print_iter: 400

# test parameters
test_dataset_path: C:\Users\user\Documents\GitHub\WiReal\amc_dataset\RML2018
load_test_path: checkpoint/few_shot/9.tar

# AMC dataset configuration
total_class: ['OOK', '4ASK', '8ASK', 'BPSK', 'QPSK', '8PSK', '16PSK', '32PSK', '16APSK', '32APSK', '64APSK', '128APSK', '16QAM', '32QAM', '64QAM', '128QAM', '256QAM', 'AM-SSB-WC', 'AM-SSB-SC', 'AM-DSB-WC', 'AM-DSB-SC', 'FM', 'GMSK', 'OQPSK']
easy_class_indice: [0, 1, 3, 4, 5, 12, 18, 20, 21, 22, 23]
difficult_class_indice: [2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19]
# few-shot learning parameters
fs_model: robustcnn # robustcnn, rewis
num_support: 5
num_query: 10